spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cjprestamos
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  servlet:
    multipart:
      max-file-size: 6MB
      max-request-size: 6MB

logging:
  level:
    org.hibernate.SQL: info

app:
  legajo:
    adjuntos:
      directorio: ./storage/legajos
      tamano-maximo-bytes: 5242880
  auth:
    bootstrap-admin:
      enabled: true
